name: midterm-transformer
seq_len: 32
hidden: 256
batch_size: 512
epochs: 100
lr: 0.0003
num_eves: 1
dataset_size: 50000

# Transformer-specific
use_transformer: true
transformer_embed_dim: 16
transformer_nhead: 2
transformer_num_layers: 1
transformer_hidden_dim: 32
