name: midterm-transformer
seq_len: 16
hidden: 256
batch_size: 512
epochs: 100
lr: 0.0008
num_eves: 1
dataset_size: 10000

# Transformer-specific
use_transformer: true
transformer_embed_dim: 32
transformer_nhead: 4
transformer_num_layers: 2
transformer_hidden_dim: 128
